name: Node.js Package

on:
  pull_request:
    types:
      - closed

jobs:
  publish-gpr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: node common/scripts/install-run-rush.js publish -p
        env:
          GPR_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}