name: Tests

on:
  push:
    branches: [development]
  pull_request:

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    outputs:
      packages: ${{ steps.filter.outputs.changes }}

    steps:
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          aform: aform/**
          atable: atable/**
          beam: beam/**

  test:
    name: ${{ matrix.package }}
    needs: changes
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: '**/config/rush/pnpm-lock.yaml'
          registry-url: https://registry.npmjs.org/

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Rush Build
        run: node common/scripts/install-run-rush.js rebuild --verbose

      - name: Run Tests
        working-directory: ./${{ matrix.package }}
        run: node ../common/scripts/install-run-rushx.js test:coverage

      - name: Coverage Report
        if: always() # generate the coverage report even if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./${{ matrix.package }}
          file-coverage-mode: 'all'
          vite-config-path: './vite.config.ts'
